### PR TITLE
FIX: Fixes #63 Conditionally permit additional GET request in POST co…

### LINKED ISSUE #63: POST requests return incorrect response code
If I issue an HTTP POST against an enabled datamodel-as-endpoint, and the resource does not exist, one is created and the module correctly scaffolds a 201 response. However, in `postHandler()` the logic attempts to address the spec for HTTP 201 responses and automatically redirect to the newly created resource at `/api/v1/My-Data-Model/<ID>.json` by the addition of a `Location` header. 

This has at least 3 issues that I can see:

1. If I wish to make exclusive use of `canCreate()` logic on my data-model, and not have `canView()` consulted _at all_, I cannot, other than to manually run `removeHeader('Location')` in my app's calling logic.
2. I can no longer assert that a 201 "Created" code is returned by the response. The 'Location' header effectively renders the response a hard-out 200. (I appreciate that this is technically correct, but AFAICT is only one way to respect the spec)
3. The data contained in the auto-returned response may be data/process heavy, something API consumers may not want for their system.

My suggestion is simple; to add an opt-out YML config option to skip the addition of the `Location` header, but where the default is to maintain current behaviour.

example:

```
        if ($this->config()->get('add_location_on_created')) {
            $urlSafeClassName = $this->sanitiseClassName(get_class($obj));
            $apiBase = $this->config()->api_base;
            $objHref = Director::absoluteURL($apiBase . "$urlSafeClassName/$obj->ID" . $type);
            $this->getResponse()->addHeader('Location', $objHref);
        }
```

### PR DESCRIPTION
**Pull request by phptek**
…ntext.

### CODE REVIEW

File: src/RestfulServer.php [hunk 1]
```diff
@@ -66,6 +66,18 @@ class RestfulServer extends Controller
...
 
+    /**
+     * Whether or not to send an additional "Location" header for POST requests
+     * to satisfy HTTP 1.1: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
+     *
+     * Note: With this enabled (the default), no POST request for resource creation
+     * will return an HTTP 201. Because of the addition of the "Location" header,
+     * all responses become a straight HTTP 200.
+     *
+     * @var boolean
```
Comment (robbieaverill) [inline src/RestfulServer.php]: Can you please add `@config`

**Comment by phptek** [comment]
Added missing `@config` (as well as to other private statics that are also missing it).

Question: AFAIK `@config` is not official phpDocumentor notation, so am I write it's an internally appropriated convention?

**Comment by robbieaverill** [comment]
>Question: AFAIK @config is not official phpDocumentor notation, so am I write it's an internally appropriated convention?

Yep, exactly 😄 thank you!
